# Generated by Django 2.1.4 on 2018-12-26 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 27, 0, 56, 46, 976328)),
        ),
    ]
