# Generated by Django 2.1.4 on 2018-12-26 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20181227_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 1, 30, 9, 393420)),
        ),
    ]
